#!c:\users\abdelrahman\documents\uni assignments\cse 3rd year\term 1\ai\ai lab 2\ai-2\scripts\python.exe
"""Small script to execute the igraph command line interface"""
from igraph.app.shell import main
main()
